### ISSUE TITLE
Allow users to have multiple roles

### ISSUE THREAD

**Issue by wongband** [bitprj/bit-backend#16]
**What feature would you like implemented**
Allow users to have the functionality of multiple roles. Allow users to potentially become a student and teacher at the same time. 
- Allow users to become multiple role models.
ex: When creating a user model, allow a feature where the user can be created as a Student model and Teacher model at the same time.

**Comment by poroia** [comment]
New update to role system: requires a decent overhaul :(

<img width="824" alt="Whiteboard 1 -01" src="https://user-images.githubusercontent.com/36049897/79058946-048bde00-7c29-11ea-84ad-79937d89f1b4.png">

All accounts will be identified with a meta `id` and the class for it can have a list of roles in which the corresponding `id`/`primary_key` for that class/role is indicated.

Example fetching system:
- Client needs to get the classroom data
Path: (using the example above)
1. client sends request
2. server decodes the meta `id/key` 37
3. using the meta `id/key` 37, retrieve the classroom's `id/key` 32
4. using the classroom's `id/key` 32, ... get classroom data
