### ISSUE TITLE
Change Login route

### ISSUE THREAD

**Issue by wongband** [bitprj/bit-backend#30]
**What feature would you like implemented**
Change the Login url from `user/login` to `/auth`

**Type of Request**
POST

**Route Url**
`user/login`

**Data Sent/Returned**
No need to change the data sent/returned

**Create/Update Postman/Documentation**
Login
- Change the url in Postman and test if it still works.
- Update the routes in the Login examples

**Comment by xerilius** [comment]
Hey @wongband 
I'm a beginner with open source, could I be assigned to it?
Thank you!

**Comment by wongband** [comment]
Hello @xerilius I assigned you the issue. You can follow the instructions in the README.md file to get your environment set up. Let me know if you have any questions :)

**Comment by xerilius** [comment]
Hi @wongband , did I need to get the environment variables from you for this issue?

**Comment by wongband** [comment]
Hi @xerilius there are steps to getting the environment variables at the end of the READEME.md

**Comment by xerilius** [comment]
@wongband messaged

**Comment by xerilius** [comment]
@wongband Testing completed,
Postman docs just need to be updated
