### ISSUE TITLE
Change the Logout route

### ISSUE THREAD

**Issue by wongband** [bitprj/bit-backend#31]
**What feature would you like implemented**
Change the Logout url from `user/logout` to `/auth`

**Type of Request**
DELETE

**Route Url**
`user/logout`

**Data Sent/Returned**
No need to change the data sent/returned

**Create/Update Postman/Documentation**
Logout
- Change the url in Postman and test if it still works.
- Update the routes in the Logout examples

**Comment by xerilius** [comment]
@wongband
