### ISSUE TITLE
Create FetchUserProfile

### ISSUE THREAD

**Issue by bitprojdev** [bitprj/bit-backend#34]
**What feature would you like implemented**
- allow user profile to be fetched with the corresponding `user_id`
- for now, since user id doesn't exist, then fetch user profile with `student_id`

**Type of Request**
GET

**Route Url**
`{{url}}/users/{{student_id}}`

**Data Sent/Returned**
- all public data corresponding to user, including name, email address, what inprogress modules, etc

**Create/Update Postman/Documentation**
FetchUserProfile

**Comment by wongband** [comment]
With the new Meta Class implemented, we can just make the route {{url}}/users/{{user_id}}
